config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources 'services' , only: %i[index new create]

  resources 'bookings' , only: %i[index new create]
  
  resources :tour_packages
  
  resources :products, only: %i[index show]

  resources :profiles, only: %i[edit update]

  authenticate :user, ->(user) { user.admin_role_type? } do
    mount Avo::Engine => '/avo'
    mount Sidekiq::Web => '/sidekiq'
  end

  # mount Avo::Engine, at: Avo.configuration.root_path
  resources :destinations, only: %i[index show]
  resources :tours , only: %i[index show]
  devise_for :users

  get :search, controller: :bookings
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  get '/blog', to: 'home#blog'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  post 'line_items', to:  "line_items#create"
  post 'update_cart', to:  "carts#update_cart"
  get 'line_items/:id', to:  "line_items#show", as: "line_item"
  delete 'line_items/:id', to:  "line_items#destroy"
  get 'checkout', to: 'checkout#index', as: 'checkout'
  
  get 'cart', to:  "carts#show", as: "cart"
  get 'empty_cart', to:  "carts#empty_cart", as: "empty_cart"
  delete 'carts/:id', to:  "carts#destroy"
  
  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true 
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :bookings_destinations
  has_many :destinations, through: :bookings_destinations  
  belongs_to :user, optional: true

  def book_destinations(destinations_ids)
    destinations_ids.reject(&:empty?).map do |id| 
      BookingsDestination.create(booking_id: self.id, destination_id: id)
    end  
  end  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end  
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/destination.rb
# frozen_string_literal: true

class Destination < ApplicationRecord
  include Attachment
  belongs_to :tour, counter_cache: true, touch: true 
  has_many :destinations_packages
  has_many :packages, through: :destinations_packages
  has_many :bookings_destinations
  has_many :bookings, through: :bookings_destinations
  has_many_attached :avatars 
  
  validates :avatars, :stay_days, presence: true
  before_save :update_slug
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart       

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  include Attachment  
  has_many :destinations_packages
  has_many :destinations, through: :destinations_packages

  validates :price, :no_of_persons, presence: true
  before_save :update_slug
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Attachment
  has_many :line_items, dependent: :destroy
  belongs_to :category
  has_many_attached :avatars do |attachable|
    attachable.variant :medium, resize_to_limit: [600, 400]
  end
  validates :price, :avatars,
            :quantity_in_hand, presence: true
  before_save :update_slug
  enum size: { 'Large': 'large', 'Medium': 'medium', 'Tiny': 'small' }
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar  
  
  validates :first_name, :last_name, presence: true
  validates :phone, numericality: true, presence: true, on: :update
  validates :address, presence: true, on: :update
end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user , optional: true  
end

app/models/subscriber.rb
# frozen_string_literal: true

class Subscriber < ApplicationRecord
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  include Attachment
  has_many :destinations, dependent: :destroy
  has_many :packages, dependent: :destroy
  belongs_to :user
  has_many_attached :avatars 

  validates :price, :avatars, presence: true
  before_save :update_slug
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :service_requests
  has_many :booking
  has_many :tours
  has_many :destinations , through: :tours
  
  has_one :shipping_address, 
    -> { where(addressable_scope: :shipping_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   

  has_one :billing_address, 
    -> { where(addressable_scope: :billing_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   
  
  accepts_nested_attributes_for :profile
  validates :profile, presence: true

  enum :role_type, { customer: 0, admin: 1 }, suffix: true
  enum :member_type, { gold: 0, diamond: 1, platinum: 2 }, suffix: true

  scope :admins, -> { where(role_type: 1) } # for avo

  after_create :send_welcome_email

  delegate :first_name, :last_name, :phone, :address , to: :profile , allow_nil: true #for reports
  
  def with_profile    
    build_profile if profile.nil?

    self
  end

  def full_name
    "#{profile.first_name} #{profile.last_name}"
  end

  def send_welcome_email
    WelcomeEmailJob.perform_in(2.minutes, self.id)
  end  
  
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  include ApplicationHelper

  def index
  end

  def new
    @service_request = ServiceRequest.new  
    @query = params[:query]   
  end
  
  def create
    @service_request = ServiceRequest.new(service_request_params)
    assign_current_user(@service_request)
    respond_to do |format|
      if @service_request.save
        format.html { redirect_to root_url , notice: 'Your request has been submited.' }        
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @service_request.errors, status: :unprocessable_entity }
      end
    end
  end  

  private

  # Only allow a list of trusted parameters through.
  def service_request_params
    params.require(:service_request).permit(:service_type, :name, :email, :phone, 
                                                :no_of_night_stays, :detail)
  end


end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/tours_helper.rb
# frozen_string_literal: true

module ToursHelper
end

app/views/services/_form.html.erb
<div class="container-fluid py-5">
  <div class="container py-5">
    <div class="text-center mb-3 pb-3">
      <h2 class="text-primary text-uppercase" style="letter-spacing: 5px;">Travel</h2>      
    </div>
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="contact-form bg-white" style="padding: 30px;">
          <div id="success"></div>
          <%= form_with(model: @service_request, url: services_path) do |p| %>
            <% if @service_request.errors.any? %>
             <div style="color: red">
               <h2><%= pluralize(@service_request.errors.count, "error") %> prohibited this profile from being saved:</h2>
               <ul>
                <% @service_request.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
               </ul>
             </div>
            <% end %>
            <div class="control-group">
              <%=p.hidden_field :service_type ,value: @query %>
              <%= p.text_field :name ,
                               class: "form-control p-4" , placeholder: "Name", 
                               required: "required"%>  
              <p class="help-block text-danger"></p>
            </div>
            <div class="control-group">                
              <%= p.text_field :email, 
                               class: "form-control p-4" , placeholder: "Email", 
                               required: "required"%>  
              <p class="help-block text-danger"></p>
            </div>
            <div class="control-group">                
              <%= p.text_field :phone, 
                               class: "form-control p-4" , placeholder: "Phone", 
                               required: "required"%>  
              <p class="help-block text-danger"></p>
            </div>
            <div class="control-group">
              <%= p.text_field :no_of_night_stays ,
                               class: "form-control p-4" , placeholder: "no of night stay", 
                               required: "required"%>  
              <p class="help-block text-danger"></p>
            </div>           
            <div class="control-group">
              <%= p.text_area :detail, class: "form-control p4" , placeholder: "detail you want", 
                               required: "required"%>  
              <p class="help-block text-danger"></p>
              <div></div>
            </div>
            <div class="text-center">             
              <%= p.submit "Make Request" ,class: "btn btn-primary py-3 px-4"%>
            </div>
          <% end%>          
        </div>        
      </div>
    </div>    
  </div>
</div>

app/views/services/index.html.erb
<!-- Header Start -->
<div class="container-fluid page-header">
  <div class="container">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 400px">
      <h3 class="display-4 text-white text-uppercase">Services</h3>
      <div class="d-inline-flex text-white">
        <p class="m-0 text-uppercase"><a class="text-white" href="">Home</a></p>
        <i class="fa fa-angle-double-right pt-1 px-3"></i>
        <p class="m-0 text-uppercase">Services</p>
      </div>
    </div>
  </div>
</div>
<!-- Header End -->

<!-- Service Start -->
<div class="container-fluid py-5">
  <div class="container pt-5 pb-3">
    <div class="text-center mb-3 pb-3">
      <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Services</h6>
      <h1>Tours & Travel Services</h1>
    </div>
    <div class="row">
      <div class="col-lg-6 col-md-6 mb-4">
        <div class="service-item bg-white text-center mb-2 py-5 px-4">
        <%= link_to new_service_path(query: 'travel') do %>
          <i class="fa fa-2x fa-route mx-auto mb-4"></i>
          <h5 class="mb-2">Travel Guide</h5>
          
          <p class="m-0">Justo sit justo eos amet tempor amet clita amet ipsum eos elitr. Amet lorem est amet labore</p>
          <% end %>
        </div>
      </div>
      <div class="col-lg-6 col-md-6 mb-4">
        <div class="service-item bg-white text-center mb-2 py-5 px-4">
          <%= link_to new_service_path(query: 'hotel') do %>
            <i class="fa fa-2x fa-hotel mx-auto mb-4"></i>
            <h5 class="mb-2">Hotel Booking</h5>
            <p class="m-0">Justo sit justo eos amet tempor amet clita amet ipsum eos elitr. Amet lorem est amet labore</p>
          <% end %> 
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Service End -->

app/views/services/new.html.erb
<%= render 'form'%>