config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources 'services' , only: %i[index new create]

  resources 'bookings' , only: %i[index new create]
  
  resources :tour_packages
  
  resources :products, only: %i[index show]

  resources :profiles, only: %i[edit update]

  authenticate :user, ->(user) { user.admin_role_type? } do
    mount Avo::Engine => '/avo'
    mount Sidekiq::Web => '/sidekiq'
  end

  # mount Avo::Engine, at: Avo.configuration.root_path
  resources :destinations, only: %i[index show]
  resources :tours , only: %i[index show]
  devise_for :users

  get :search, controller: :bookings
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  get '/blog', to: 'home#blog'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  post 'line_items', to:  "line_items#create"
  post 'update_cart', to:  "carts#update_cart"
  get 'line_items/:id', to:  "line_items#show", as: "line_item"
  delete 'line_items/:id', to:  "line_items#destroy"
  get 'checkout', to: 'checkout#index', as: 'checkout'
  
  get 'cart', to:  "carts#show", as: "cart"
  get 'empty_cart', to:  "carts#empty_cart", as: "empty_cart"
  delete 'carts/:id', to:  "carts#destroy"
  
  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true 
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :bookings_destinations
  has_many :destinations, through: :bookings_destinations  
  belongs_to :user, optional: true

  def book_destinations(destinations_ids)
    destinations_ids.reject(&:empty?).map do |id| 
      BookingsDestination.create(booking_id: self.id, destination_id: id)
    end  
  end  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end  
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/destination.rb
# frozen_string_literal: true

class Destination < ApplicationRecord
  include Attachment
  belongs_to :tour, counter_cache: true, touch: true 
  has_many :destinations_packages
  has_many :packages, through: :destinations_packages
  has_many :bookings_destinations
  has_many :bookings, through: :bookings_destinations
  has_many_attached :avatars 
  
  validates :avatars, :stay_days, presence: true
  before_save :update_slug
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart       

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  include Attachment  
  has_many :destinations_packages
  has_many :destinations, through: :destinations_packages

  validates :price, :no_of_persons, presence: true
  before_save :update_slug
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Attachment
  has_many :line_items, dependent: :destroy
  belongs_to :category
  has_many_attached :avatars do |attachable|
    attachable.variant :medium, resize_to_limit: [600, 400]
  end
  validates :price, :avatars,
            :quantity_in_hand, presence: true
  before_save :update_slug
  enum size: { 'Large': 'large', 'Medium': 'medium', 'Tiny': 'small' }
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar  
  
  validates :first_name, :last_name, presence: true
  validates :phone, numericality: true, presence: true, on: :update
  validates :address, presence: true, on: :update
end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user , optional: true  
end

app/models/subscriber.rb
# frozen_string_literal: true

class Subscriber < ApplicationRecord
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  include Attachment
  has_many :destinations, dependent: :destroy
  has_many :packages, dependent: :destroy
  belongs_to :user
  has_many_attached :avatars 

  validates :price, :avatars, presence: true
  before_save :update_slug
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :service_requests
  has_many :booking
  has_many :tours
  has_many :destinations , through: :tours
  
  has_one :shipping_address, 
    -> { where(addressable_scope: :shipping_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   

  has_one :billing_address, 
    -> { where(addressable_scope: :billing_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   
  
  accepts_nested_attributes_for :profile
  validates :profile, presence: true

  enum :role_type, { customer: 0, admin: 1 }, suffix: true
  enum :member_type, { gold: 0, diamond: 1, platinum: 2 }, suffix: true

  scope :admins, -> { where(role_type: 1) } # for avo

  after_create :send_welcome_email

  delegate :first_name, :last_name, :phone, :address , to: :profile , allow_nil: true #for reports
  
  def with_profile    
    build_profile if profile.nil?

    self
  end

  def full_name
    "#{profile.first_name} #{profile.last_name}"
  end

  def send_welcome_email
    WelcomeEmailJob.perform_in(2.minutes, self.id)
  end  
  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/tours_helper.rb
# frozen_string_literal: true

module ToursHelper
end

app/views/shared/_flash_messages.erb
<% if notice %>
  <div class="alert alert-info mt-4 mb-5" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% elsif  alert %>  
  <div class="alert alert-warning mt-4 mb-5" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 py-5 px-sm-3 px-lg-5" style="margin-top: 90px;">
    <div class="row pt-5">
        <div class="col-lg-3 col-md-6 mb-5">
            <a href="" class="navbar-brand">
                <h1 class="text-primary"><span class="text-white">TRAVEL</span>ER</h1>
            </a>
            <p>Sed ipsum clita tempor ipsum ipsum amet sit ipsum lorem amet labore rebum lorem ipsum dolor. No sed vero lorem dolor dolor</p>
            <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Follow Us</h6>
            <div class="d-flex justify-content-start">
              <%= link_to "#", class: "btn btn-outline-primary btn-square mr-2" do %>
                <i class="fab fa-twitter"></i> 
              <% end %>
              <%= link_to "#", class: "btn btn-outline-primary btn-square mr-2" do %>
                <i class="fab fa-facebook-f"></i> 
              <% end %>
              <%= link_to "#", class: "btn btn-outline-primary btn-square mr-2" do %>
                <i class="fab fa-linkedin-in"></i> 
              <% end %>
              <%= link_to "#", class: "btn btn-outline-primary btn-square" do %>
                <i class="fab fa-instagram"></i> 
              <% end %>                
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Our Services</h5>
            <div class="d-flex flex-column justify-content-start">
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Destination</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Services</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Packages</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Guides</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Testimonial</a>
                <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>Blog</a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Usefull Links</h5>
            <div class="d-flex flex-column justify-content-start">
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Destination</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Services</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Packages</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Guides</a>
                <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Testimonial</a>
                <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>Blog</a>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 mb-5">
            <h5 class="text-white text-uppercase mb-4" style="letter-spacing: 5px;">Contact Us</h5>
            <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
            <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
            <p><i class="fa fa-envelope mr-2"></i>info@example.com</p>
            <h6 class="text-white text-uppercase mt-4 mb-3" style="letter-spacing: 5px;">Newsletter</h6>
            <div class="w-100">
                <div class="input-group">
                    <input type="text" class="form-control border-light" style="padding: 25px;" placeholder="Your Email">
                    <div class="input-group-append">
                        <button class="btn btn-primary px-3">Sign Up</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid bg-dark text-white border-top py-4 px-sm-3 px-md-5" style="border-color: rgba(256, 256, 256, .1) !important;">
    <div class="row">
        <div class="col-lg-6 text-center text-md-left mb-3 mb-md-0">
            <p class="m-0 text-white-50">Copyright &copy; <a href="#">Domain</a>. All Rights Reserved.</a>
            </p>
        </div>
        <div class="col-lg-6 text-center text-md-right">
            <p class="m-0 text-white-50">Designed by <a href="#">HTML </a>
            </p>
        </div>
    </div>
</div>
<!-- Footer End -->


<!-- Back to Top -->
<a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>

app/views/shared/_header.html.erb
<div class="container-fluid bg-light pt-3 d-none d-lg-block">
  <div class="container">
    <div class="row">
      
      <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
        <div class="d-inline-flex align-items-center">
          <p><i class="fa fa-envelope mr-2"></i>info@tour.com</p>
          <p class="text-body px-3">|</p>
          <p><i class="fa fa-phone-alt mr-2"></i>+92 345 4145256</p>
        </div>
      </div>
      
      <div class="col-lg-6 text-center text-lg-right">
        <div class="d-inline-flex align-items-center" >
          <%= link_to "#", class: "text-primary px-3" do %>
            <i class="fab fa-facebook-f"></i> 
          <% end %>
          <%= link_to "#", class: "text-primary px-3" do %>
            <i class="fab fa-twitter"></i> 
          <% end %>
          <%= link_to "#", class: "text-primary px-3" do %>
            <i class="fab fa-linkedin-in"></i> 
          <% end %>
          <%= link_to "#", class: "text-primary px-3" do %>
            <i class="fab fa-instagram"></i> 
          <% end %>
          <%= link_to "#", class: "text-primary px-3" do %>
            <i class="fab fa-youtube"></i> 
          <% end %>   
          <%= link_to cart_path, id: 'cart',class: "text-primary px-3" do %>
            <i class="fa fa-shopping-cart"></i> <%= line_items %>
          <% end %>                                 
        </div>
      </div>
    </div>
  </div>
</div>




<div class="container-fluid position-relative nav-bar p-0">
  <div class="container-lg position-relative p-0 px-lg-3" style="z-index: 9;">
    <nav class="navbar navbar-expand-lg bg-light navbar-light shadow-lg py-3 py-lg-0 pl-3 pl-lg-5">
      <a href="" class="navbar-brand">
        <h1 class="m-0 text-primary"><span class="text-dark">Tours&</span>Travel</h1>
      </a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
         <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-between px-3" id="navbarCollapse">
        <div class="navbar-nav ml-auto py-0">
        
          <%= link_to "Home" , root_path, class: home_active %>              
          <%= link_to "Shop" , products_path, class: shop_active %>                                                                  
          <%= link_to "Services" , services_path, class: services_active %>                                        
          <%= link_to "Tour packages" , tour_packages_path, class: tours_active %>
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
              <div class="dropdown-menu border-0 rounded-0 m-0">
                <%= link_to "Blog" , blog_path, class: "dropdown-item" %>
                <%= link_to "About" , about_path, class: "dropdown-item" %>
                <%= link_to "Contact" , contact_path, class: "dropdown-item" %>
                <%= link_to "Travel Guides" , "#", class: "dropdown-item" %>
              </div>
          </div>
          <%= collapsible_welcome_path %>
        </div>
      </div>
    </nav>
  </div>
</div>

app/views/shared/_profile_image.html.erb
<% if avatar.class.name == "String"%>
  <%= cl_image_tag(avatar, width: dimension, height: dimension, crop: :scale) %>
<% else %>
  <%= cl_image_tag(avatar.key, width: dimension, height: dimension, crop: :scale) %>
<% end %> 

app/views/shared/_sign_in_nav.html.erb
<div class="nav-item dropdown">
  <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
    <%= render partial: 'shared/profile_image', locals: {dimension: 20}%>  
  </a> 
  <div class="dropdown-menu border-0 rounded-0 m-0">    
    <%= link_to "Profile" , edit_profile_path(Current.user.profile), 
        class: "dropdown-item" %>
    <%= link_to "Admin" , '/avo', class: "dropdown-item" if admin?%>
    <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } , 
        class: "dropdown-item"%>                           
  </div>
</div>

app/views/shared/_sign_up.html.erb
<div class="container-fluid bg-registration py-5" style="margin: 90px 0;">
  <div class="container py-5">
    <div class="row align-items-center">
      <div class="col-lg-7 mb-5 mb-lg-0">
        <div class="mb-4">
          <h6 class="text-primary text-uppercase" style="letter-spacing: 5px;">Mega Offer</h6>
          <h1 class="text-white"><span class="text-primary">30% OFF</span> For Honeymoon</h1>
        </div>
        <p class="text-white">Invidunt lorem justo sanctus clita. Erat lorem labore ea, justo dolor lorem ipsum ut sed eos, ipsum et dolor kasd sit ea justo. Erat justo sed sed diam. Ea et erat ut sed diam sea ipsum est dolor</p>
        <ul class="list-inline text-white m-0">
          <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Labore eos amet dolor amet diam</li>
          <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Etsea et sit dolor amet ipsum</li>
          <li class="py-2"><i class="fa fa-check text-primary mr-3"></i>Diam dolor diam elitripsum vero.</li>
        </ul>
      </div>      
      <div class="col-lg-5">
        <div class="card border-0">
          <div class="card-header bg-primary text-center p-4">
            <h1 class="text-white m-0">Sign Up Now</h1>
          </div>
          <div class="card-body rounded-bottom bg-white p-5">
            <div class="form-group"> </div>
            <%= form_for([@user, @user.with_profile], url: registration_path(@user)) do |f| %>
              <div class="control-group">
                <%= f.email_field :email, autofocus: true, autocomplete: "email" ,
                                  class: "form-control p-4" , placeholder: "Email", 
                                  required: "required"%>  
                <p class="help-block text-danger"></p>
              </div>
              <%= f.fields_for :profile do |p| %>
                <div class="control-group">
                  <%= p.text_field :first_name ,
                                   class: "form-control p-4" , placeholder: "First name", 
                                   required: "required"%>  
                  <p class="help-block text-danger"></p>
                </div>
                <div class="control-group">                
                  <%= p.text_field :last_name, 
                                   class: "form-control p-4" , placeholder: "Last name", 
                                   required: "required"%>  
                  <p class="help-block text-danger"></p>
                </div>
              <% end %>
              <div class="control-group">
                <%= f.password_field :password, autocomplete: "new-password",
                                     class: "form-control p-4" , placeholder: "Password min 6 length", 
                                     required: "required"%>  
                <p class="help-block text-danger"></p>
              </div>
              <div class="control-group">
                <%= f.password_field :password_confirmation, autocomplete: "new-password" ,
                                     class: "form-control p-4" , placeholder: "Confirm password", 
                                     required: "required"%>  
                <p class="help-block text-danger"></p>
              </div>
              <div> 
                <%= f.submit "Sign up" ,class: "btn btn-primary btn-block py-3"%>
              </div>  
            <% end %>            
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_slider.html.erb
<div class="container-fluid p-0">
    <div id="header-carousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% avatars ||=  ['awesome-1.jpg','awesome-2.jpg'] %>        
        <% avatars.map.with_index do |item,index| %>              
          <div class="carousel-item <%= index == 0 ? "active" : "" %>">
            <%if ['awesome-1.jpg','awesome-2.jpg'].include? item%>
              <%= image_tag item ,class: 'w-100',alt: "Image", height: '500' %>
            <% else %>  
              <%= cl_image_tag item.key ,class: 'w-100',alt: "Image", height: 500, width: 1000 ,crop: :scale%>
            <% end %>   
              <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                <div class="p-3" style="max-width: 900px;">
                  <h4 class="text-white text-uppercase mb-md-3">Tours & Travel</h4>
                  <h1 class="display-3 text-white mb-md-4">
                    <%= index == 0 ? "Let's Discover The Pakistan Together" : 
                          "Discover Amazing Places With Us" %> 
                  </h1>
                  
                  <%= link_to "Book Now", new_booking_path, class: "btn btn-primary py-md-3 px-md-5 mt-2" %>
                </div>
              </div>
          </div>
      <% index == 0 ? "</div>" : "" %>
        
        <a class="carousel-control-<%= index == 0 ? "prev" : "next" %>" href="#header-carousel" data-slide="<%= index == 0 ? "prev" : "next" %>">
          <div class="btn btn-dark" style="width: 45px; height: 45px;">
            <span class="carousel-control-<%= index == 0 ? "prev" : "next" %>-icon mb-n2"></span>
          </div>
        </a>
      <% end %>
    </div>
</div>