config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources 'services' , only: %i[index new create]

  resources 'bookings' , only: %i[index new create]
  
  resources :tour_packages
  
  resources :products, only: %i[index show]

  resources :profiles, only: %i[edit update]

  authenticate :user, ->(user) { user.admin_role_type? } do
    mount Avo::Engine => '/avo'
    mount Sidekiq::Web => '/sidekiq'
  end

  # mount Avo::Engine, at: Avo.configuration.root_path
  resources :destinations, only: %i[index show]
  resources :tours , only: %i[index show]
  devise_for :users

  get :search, controller: :bookings
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  get '/blog', to: 'home#blog'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  post 'line_items', to:  "line_items#create"
  post 'update_cart', to:  "carts#update_cart"
  get 'line_items/:id', to:  "line_items#show", as: "line_item"
  delete 'line_items/:id', to:  "line_items#destroy"
  get 'checkout', to: 'checkout#index', as: 'checkout'
  
  get 'cart', to:  "carts#show", as: "cart"
  get 'empty_cart', to:  "carts#empty_cart", as: "empty_cart"
  delete 'carts/:id', to:  "carts#destroy"
  
  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true 
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :bookings_destinations
  has_many :destinations, through: :bookings_destinations  
  belongs_to :user, optional: true

  def book_destinations(destinations_ids)
    destinations_ids.reject(&:empty?).map do |id| 
      BookingsDestination.create(booking_id: self.id, destination_id: id)
    end  
  end  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end  
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/destination.rb
# frozen_string_literal: true

class Destination < ApplicationRecord
  include Attachment
  belongs_to :tour, counter_cache: true, touch: true 
  has_many :destinations_packages
  has_many :packages, through: :destinations_packages
  has_many :bookings_destinations
  has_many :bookings, through: :bookings_destinations
  has_many_attached :avatars 
  
  validates :avatars, :stay_days, presence: true
  before_save :update_slug
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart       

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  include Attachment  
  has_many :destinations_packages
  has_many :destinations, through: :destinations_packages

  validates :price, :no_of_persons, presence: true
  before_save :update_slug
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Attachment
  has_many :line_items, dependent: :destroy
  belongs_to :category
  has_many_attached :avatars do |attachable|
    attachable.variant :medium, resize_to_limit: [600, 400]
  end
  validates :price, :avatars,
            :quantity_in_hand, presence: true
  before_save :update_slug
  enum size: { 'Large': 'large', 'Medium': 'medium', 'Tiny': 'small' }
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar  
  
  validates :first_name, :last_name, presence: true
  validates :phone, numericality: true, presence: true, on: :update
  validates :address, presence: true, on: :update
end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user , optional: true  
end

app/models/subscriber.rb
# frozen_string_literal: true

class Subscriber < ApplicationRecord
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  include Attachment
  has_many :destinations, dependent: :destroy
  has_many :packages, dependent: :destroy
  belongs_to :user
  has_many_attached :avatars 

  validates :price, :avatars, presence: true
  before_save :update_slug
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :service_requests
  has_many :booking
  has_many :tours
  has_many :destinations , through: :tours
  
  has_one :shipping_address, 
    -> { where(addressable_scope: :shipping_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   

  has_one :billing_address, 
    -> { where(addressable_scope: :billing_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   
  
  accepts_nested_attributes_for :profile
  validates :profile, presence: true

  enum :role_type, { customer: 0, admin: 1 }, suffix: true
  enum :member_type, { gold: 0, diamond: 1, platinum: 2 }, suffix: true

  scope :admins, -> { where(role_type: 1) } # for avo

  after_create :send_welcome_email

  delegate :first_name, :last_name, :phone, :address , to: :profile , allow_nil: true #for reports
  
  def with_profile    
    build_profile if profile.nil?

    self
  end

  def full_name
    "#{profile.first_name} #{profile.last_name}"
  end

  def send_welcome_email
    WelcomeEmailJob.perform_in(2.minutes, self.id)
  end  
  
end

app/controllers/avo/carts_controller.rb
# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
class Avo::CartsController < Avo::ResourcesController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show       
    cart_with_line_items    
  end

  def update_cart        
    params[:line_item][:id].each_with_index do |item, index| 
      item = LineItem.find_by(id: params[:line_item][:id][index])
      item.update(quantity: params[:line_item][:quantity][index]) if item.present?
    end    
  
    cart_with_line_items
    respond_to do |format|   
      format.turbo_stream
    end  
  end  

  def empty_cart    
    @current_cart.line_items.delete_all    
    redirect_to cart_path, alert: 'Cart is empty.'   
  end  

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end

  
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/packages_helper.rb
# frozen_string_literal: true

module PackagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/tours_helper.rb
# frozen_string_literal: true

module ToursHelper
end

app/views/carts/_show.html.erb
<section class="cart_area" >
  <% if line_items.present?%>
    <%= form_with(model: LineItem.new, url: update_cart_path, method: :post) do |form| %>                       
        <div class="container">
          <div class="cart_inner">
            <div class="table-responsive">
              <table class="table">
              
                <thead>
                  <tr>
                    <th scope="col">Product</th>
                    <th scope="col">Price</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Total</th>                
                  </tr>
                </thead>
                <tbody>

                                  
                <% line_items.each do |item|%>
                  <tr>
                    <td>
                      <div class="media">
                        <div class="d-flex">
                          <%= cl_image_tag(item.product.avatars[0].key, height: 100, Width: 150, alt: "", crop: :scale) %>                      
                        </div>
                        <div class="media-body">
                          <p><%= item.product.title%></p>
                        </div>
                      </div>
                    </td>
                    <td>
                      <h5><%= item.product.id%>$<%= item.product.price%></h5>
                    </td> 
                    <td>     
                      <div class="product_count" id=<%=item.id%> data-controller="add-product">                      
                        <%= text_field_tag "line_item[quantity][]", "#{item.quantity}", id: "input-#{item.id}", class:"input-text qty" %>
                        <%= hidden_field_tag "line_item[id][]", "#{item.id}" %>      
                        <div id="btn-inc-<%=item.id%>" data-action='click->add-product#addQuantityBulk'>
                        <button 
                          class="increase items-count"
                          type="button"
                          >
                        <i class="fas fa-angle-up"></i>
                        </button>
                        </div>
                        <button id="btn-dec-<%=item.id%>" data-action='click->add-product#decreaseQuantityBulk'               
                          class="reduced items-count"
                          type="button"
                          >
                        <i class="fas fa-angle-down"></i>
                        </button>         
                      </div>
                    
                    </td>
                    
                    <td>
                      <h5>$<%= item.total_price %></h5>
                    </td>
                  
                    <td data-controller="add-product">
                      <h5><%= link_to "Remove", "javascript:;", id: "#{item.id}" , data: {action: 'click->add-product#remove'}  %> </h5>
                    </td>
                  </tr>
                <% end %>                    
                  
                    <tr class="bottom_button">
                      <td>                  
                        <%= form.submit "Update Cart"%>
                      </td>
                      <td> <%=link_to "Empty cart", empty_cart_path, class: "main_btn" %> </td>
                      <td></td>                
                    </tr>
                    <tr>
                      <td></td>
                      <td></td>
                      <td>
                        <h5>Subtotal</h5>
                      </td>
                      <td>
                        <h5 id="total">$<%= @sub_total %></h5>
                      </td>
                    </tr>

                  </div>
                  
                    <tr class="shipping_area">
                      <td></td>
                      <td></td>
                      <td>
                        <h5>Shipping</h5>
                      </td>
                      <td>
                        <div class="form-check" data-controller="add-product">                      
                          <input class="form-check-input" type="radio" value="free" name="flexRadioDefault" id="free" checked data-action="add-product#toggel">                      
                          <label class="form-check-label" for="flexRadioDefault1">
                            Free Shipping 
                          </label>
                        </div>
                        <div class="form-check" data-controller="add-product">                      
                          <input class="form-check-input" type="radio" value="fast" name="flexRadioDefault" id="fast" data-action="add-product#toggel">                      
                          <label class="form-check-label" for="flexRadioDefault2">
                            Fast Shipping $5
                          </label>
                        </div>
                      </td>               
                    </tr>
                    
                    <tr>
                      <td></td>
                      <td></td>
                      <td>
                        <h5>Total</h5>
                      </td>
                      <td>
                        <h5>$<span id="total_with_shipping"><%= @sub_total%></span></h5>
                      </td>
                    </tr>
                  
                    <tr class="out_button_area">
                      <td></td>
                      <td></td>
                      <td></td>
                      <td>
                      </td>
                    </tr>

                    <tr class="out_button_area">
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>
                      <div class="checkout_btn_inner">
                        <a class="gray_btn" href="/products">Continue Shopping</a>
                        <a class="main_btn" href="#">Proceed to checkout</a>
                      </div>
                    </td>
                  </tr>
                
                </tbody>
              </table>
            </div>
          </div>
        </div>
    <% end %>
  <% end %>
</section>

app/views/carts/show.html.erb
<div id="items">
  <%= render partial: "carts/show", locals: {line_items: @line_items} %>
</div>

app/views/carts/update_cart.turbo_stream.erb
<%= turbo_stream.update("icons",
            partial: "shared/header") %>


<%= turbo_stream.update("items",
            partial: "carts/show",
            locals: { line_items: @line_items }) %>            


<%= turbo_stream.update("flash",
            partial: "shared/flash_messages",
            locals: { notice: "Cart updated." }) %>            