config/routes.rb
# frozen_string_literal: true
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources 'services' , only: %i[index new create]

  resources 'bookings' , only: %i[index new create]
  
  resources :tour_packages
  
  resources :products, only: %i[index show]

  resources :profiles, only: %i[edit update]

  authenticate :user, ->(user) { user.admin_role_type? } do
    mount Avo::Engine => '/avo'
    mount Sidekiq::Web => '/sidekiq'
  end

  # mount Avo::Engine, at: Avo.configuration.root_path
  resources :destinations, only: %i[index show]
  resources :tours , only: %i[index show]
  devise_for :users

  get :search, controller: :bookings
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  get '/blog', to: 'home#blog'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  post 'line_items', to:  "line_items#create"
  post 'update_cart', to:  "carts#update_cart"
  get 'line_items/:id', to:  "line_items#show", as: "line_item"
  delete 'line_items/:id', to:  "line_items#destroy"
  get 'checkout', to: 'checkout#index', as: 'checkout'
  
  get 'cart', to:  "carts#show", as: "cart"
  get 'empty_cart', to:  "carts#empty_cart", as: "empty_cart"
  delete 'carts/:id', to:  "carts#destroy"
  
  root 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true 
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :bookings_destinations
  has_many :destinations, through: :bookings_destinations  
  belongs_to :user, optional: true

  def book_destinations(destinations_ids)
    destinations_ids.reject(&:empty?).map do |id| 
      BookingsDestination.create(booking_id: self.id, destination_id: id)
    end  
  end  
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items

  # LOGIC
  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum+= line_item.total_price
    end
    return sum
  end  
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true
end

app/models/current.rb
# frozen_string_literal: true

class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/destination.rb
# frozen_string_literal: true

class Destination < ApplicationRecord
  include Attachment
  belongs_to :tour, counter_cache: true, touch: true 
  has_many :destinations_packages
  has_many :packages, through: :destinations_packages
  has_many :bookings_destinations
  has_many :bookings, through: :bookings_destinations
  has_many_attached :avatars 
  
  validates :avatars, :stay_days, presence: true
  before_save :update_slug
end

app/models/image.rb
# frozen_string_literal: true

class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart       

  def total_price
    self.quantity * self.product.price
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  include Attachment  
  has_many :destinations_packages
  has_many :destinations, through: :destinations_packages

  validates :price, :no_of_persons, presence: true
  before_save :update_slug
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Attachment
  has_many :line_items, dependent: :destroy
  belongs_to :category
  has_many_attached :avatars do |attachable|
    attachable.variant :medium, resize_to_limit: [600, 400]
  end
  validates :price, :avatars,
            :quantity_in_hand, presence: true
  before_save :update_slug
  enum size: { 'Large': 'large', 'Medium': 'medium', 'Tiny': 'small' }
end

app/models/profile.rb
# frozen_string_literal: true

class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :avatar  
  
  validates :first_name, :last_name, presence: true
  validates :phone, numericality: true, presence: true, on: :update
  validates :address, presence: true, on: :update
end

app/models/service_request.rb
class ServiceRequest < ApplicationRecord
  belongs_to :user , optional: true  
end

app/models/subscriber.rb
# frozen_string_literal: true

class Subscriber < ApplicationRecord
end

app/models/tour.rb
# frozen_string_literal: true

class Tour < ApplicationRecord
  include Attachment
  has_many :destinations, dependent: :destroy
  has_many :packages, dependent: :destroy
  belongs_to :user
  has_many_attached :avatars 

  validates :price, :avatars, presence: true
  before_save :update_slug
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile, dependent: :destroy
  has_many :service_requests
  has_many :booking
  has_many :tours
  has_many :destinations , through: :tours
  
  has_one :shipping_address, 
    -> { where(addressable_scope: :shipping_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   

  has_one :billing_address, 
    -> { where(addressable_scope: :billing_address) }, 
    as: :addressable, 
    class_name: 'Address', 
    dependent: :destroy   
  
  accepts_nested_attributes_for :profile
  validates :profile, presence: true

  enum :role_type, { customer: 0, admin: 1 }, suffix: true
  enum :member_type, { gold: 0, diamond: 1, platinum: 2 }, suffix: true

  scope :admins, -> { where(role_type: 1) } # for avo

  after_create :send_welcome_email

  delegate :first_name, :last_name, :phone, :address , to: :profile , allow_nil: true #for reports
  
  def with_profile    
    build_profile if profile.nil?

    self
  end

  def full_name
    "#{profile.first_name} #{profile.last_name}"
  end

  def send_welcome_email
    WelcomeEmailJob.perform_in(2.minutes, self.id)
  end  
  
end

app/controllers/avo/products_controller.rb
# frozen_string_literal: true

# This controller has been generated to enable Rails' resource routes.
# More information on https://docs.avohq.io/2.0/controllers.html
module Avo
  class ProductsController < Avo::ResourcesController
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[show]

  # GET /products or /products.json
  def index
    @products = Product.includes([:category , avatars_attachments: :blob])
  end

  # GET /products/1 or /products/1.json
  def show    
    @line_item = LineItem.new
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find_by_slug(params[:id])
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/packages_helper.rb
# frozen_string_literal: true

module PackagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/helpers/tours_helper.rb
# frozen_string_literal: true

module ToursHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.text_field :number %>
  </div>

  <div>
    <%= form.label :category_id, style: "display: block" %>
    <%= form.text_field :category_id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :quantity_in_hand, style: "display: block" %>
    <%= form.number_field :quantity_in_hand %>
  </div>

  <div>
    <%= form.label :detail, style: "display: block" %>
    <%= form.text_area :detail %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.text_field :size %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-lg-4 col-md-6" id="<%= dom_id product %>">
  <div class="single-product"> 
    <div class="product-img">
      <%= cl_image_tag(product.avatars[0].key, height: 261, class: "card-img", alt: "", crop: :scale) %>
      <div class="p_icon">
        
        <%= button_to line_items_path(:product_id => product.id),remote: true, method: :post do %>
          <i class="fa fa-shopping-cart"></i>
        <% end %>   
        
        <%= button_to line_items_path(:product_id => product.id), method: :post do %>
          <i class="fa fa-heart"></i>
        <% end %>           
        
      </div>
    </div>
    <div class="product-btm">      
      <h4><%= link_to product.title, product_path(product), class: "d-block"%></h4>
      <div class="mt-3">
        <span class="mr-4">$<%= product.price%></span>
        <del>save 35%</del>
      </div>
    </div>
  </div>
</div>  

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="container">
      <div class="banner_content d-md-flex justify-content-between align-items-center">
        <div class="mb-3 mb-md-0">
          <h2>Shop Category</h2>
          <p>Very us move be blessed multiply night</p>
        </div>
        <div class="page_link">
          <a href="index.html">Home</a>
          <a href="category.html">Shop</a>
          <a href="category.html">Women Fashion</a>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="cat_product_area section_gap">
  <div class="container">
    <div class="row flex-row-reverse">
      <div class="col-lg-9">
        <div class="product_top_bar">
          <div class="left_dorp">
            <select class="sorting">
              <option value="1">Default sorting</option>
              <option value="2">Default sorting 01</option>
              <option value="4">Default sorting 02</option>
            </select>
            <select class="show">
              <option value="1">Show 12</option>
              <option value="2">Show 14</option>
              <option value="4">Show 16</option>
            </select>
          </div>
        </div>
        <div class="latest_product_inner">
          <div class="row">
            <%@products.each do |product|%>
              <%= render product%>
            <%end%> 
          </div>
        </div>
      </div>
      <div class="col-lg-3">
        <div class="left_sidebar_area">
          <aside class="left_widgets p_filter_widgets">
            <div class="l_w_title">
              <h3>Browse Categories</h3>
            </div>
            <div class="widgets_inner">
              <ul class="list" style="list-style: none;">
                <li>
                  <a href="#">Frozen Fish</a>
                </li>
                <li>
                  <a href="#">Dried Fish</a>
                </li>
                <li>
                  <a href="#">Fresh Fish</a>
                </li>
                <li>
                  <a href="#">Meat Alternatives</a>
                </li>
                <li>
                  <a href="#">Fresh Fish</a>
                </li>
                <li>
                  <a href="#">Meat Alternatives</a>
                </li>
                <li>
                  <a href="#">Meat</a>
                </li>
              </ul>
            </div>
          </aside>
          
          <aside class="left_widgets p_filter_widgets">
            <div class="l_w_title">
              <h3>Price Filter</h3>
            </div>
            <div class="widgets_inner">
              <div class="range_item">
                <div id="slider-range"></div>
                <div class="">
                  <label for="amount">Price : </label>
                  <input type="text" id="amount" />
                </div>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<section class="banner_area">
  <div class="banner_inner d-flex align-items-center">
    <div class="container">
      <div
        class="banner_content d-md-flex justify-content-between align-items-center"
        >
        <div class="mb-3 mb-md-0">
          <h2>Product Details</h2>
          <p><%=@product.title%></p>
        </div>
        <div class="page_link">
          <a href="index.html">Home</a>
          <a href="single-product.html">Product Details</a>
        </div>
      </div>
    </div>
  </div>
</section>


<div class="product_image_area">
  <div class="container">
    <div class="row s_product_inner">
      <div class="col-lg-6">
        <div class="s_product_img">
          <div
            id="carouselExampleIndicators"
            class="carousel slide"
            data-ride="carousel"
            >
            <ol class="carousel-indicators">
              <% @product.avatars.each_with_index do |avtr,index| %>
                <li
                  data-target="#carouselExampleIndicators"
                  data-slide-to="<%=index%>"
                  class= <%= index == 0 ? "active" : ""%>
                  >
                  <%= cl_image_tag(avtr.key, height: 60, Width: 60, alt: "", crop: :scale) %>
                  
                </li>
              <% end %>              
            </ol>
            <div class="carousel-inner">
              <% @product.avatars.each_with_index do |avtr,index| %>
              <div class="carousel-item <%= index == 0 ? "active" : ""%>">
                    <%= cl_image_tag(avtr.key, height: 600, Width: 555, class: "d-block w-100", alt: "", crop: :scale) %>
                
              </div>
              <% end %>        
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
        <div class="s_product_text">
          <h3><%=@product.title%></h3>
          <h2>$<%=@product.price%></h2>
          <ul class="list">
            <li>
              <a class="active" href="#">
              <span>Category</span> : <%=@product.category.name%></a
                >
            </li>
            <li>
              <a href="#"> <span>Availibility</span> : In Stock</a>
            </li>
          </ul>
          <p>
            <%=@product.detail%>
          </p>
          
          <%= form_with(model: @line_item) do |p| %>
          
            <div class="product_count" data-controller="add-product">
            
              <label for="qty">Quantity:</label>
              <%= p.hidden_field :product_id, value: @product.id %>         
              <%= p.text_field :quantity, id: "sst", 
                  class:"input-text qty", value: "1", data: { add_product_target: :quantity }  %>         
              <button data-action='click->add-product#addQuantity'               
                class="increase items-count"
                type="button"
                >
              <i class="fas fa-angle-up"></i>
              </button>
              <button data-action='click->add-product#decreaseQuantity'               
                class="reduced items-count"
                type="button"
                >
              <i class="fas fa-angle-down"></i>
              </button>         
            
            </div>
            
            <div class="card_area">
              <%= p.submit "Add to Cart",class: "main_btn"%>            
              <a class="icon_btn" href="#">
              <i class="fa fa-diamond"></i>
              </a>
              <a class="icon_btn" href="#">
              <i class="fa fa-heart"></i>
              </a>
            </div>
          
          <% end %>  

        </div>
      </div>
    </div>
  </div>
</div>

<section class="product_description_area">
  <div class="container">
    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item">
        <a
          class="nav-link"
          id="home-tab"
          data-toggle="tab"
          href="#home"
          role="tab"
          aria-controls="home"
          aria-selected="true"
          >Description</a
          >
      </li>
      <li class="nav-item">
        <a
          class="nav-link"
          id="profile-tab"
          data-toggle="tab"
          href="#profile"
          role="tab"
          aria-controls="profile"
          aria-selected="false"
          >Specification</a
          >
      </li>      
    </ul>
    
    <div class="tab-content" id="myTabContent">
      <div
        class="tab-pane fade show active"
        id="home"
        role="tabpanel"
        aria-labelledby="home-tab"
        >
        <p>
          <%=@product.detail%>
        </p>        
      </div>
      <div
        class="tab-pane fade"
        id="profile"
        role="tabpanel"
        aria-labelledby="profile-tab"
        >
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td>
                  <h5>Width</h5>
                </td>
                <td>
                  <h5>128mm</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Height</h5>
                </td>
                <td>
                  <h5>508mm</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Depth</h5>
                </td>
                <td>
                  <h5>85mm</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Weight</h5>
                </td>
                <td>
                  <h5>52gm</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Quality checking</h5>
                </td>
                <td>
                  <h5>yes</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Freshness Duration</h5>
                </td>
                <td>
                  <h5>03days</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>When packeting</h5>
                </td>
                <td>
                  <h5>Without touch of hand</h5>
                </td>
              </tr>
              <tr>
                <td>
                  <h5>Each Box contains</h5>
                </td>
                <td>
                  <h5>60pcs</h5>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</section>